Added functions replace and search
HolyHol/study pull request #1
Opened 2021-01-07 18:03 UTC by HolyHol

2021-01-14 17:07 UTC, nut4k1 requested changes
Mainly looks good. Try to implement algorithm, not to create it.

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +      end
First, this methods are identical
Second, in Ruby if there are two methods with the same name, last one will be used (even if they have different interfaces. e.g. in Java it's called _overload_, I suppose).

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +
no need empty line before **return**, check with rubocop

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +          list[0] # base case
no need to check for that case, algorithm suppose to work with all valid cases

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +        sub_array = replaces_positive_array(array[1..-1], max_array_new)
you are loosing first element here

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +        end
please, run rubocop for style checks & fixes

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +      return -1
main idea of this binary search:
-  data is sorted
- complexity (max iterations) should be equal to **log2(N)**

base on your loop condition `while low <= high` it is **N-1**

P.S.: you can check it by using count variable and increasing it with each iteration

2021-01-14 17:07 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +        end
you no need to use recursive here

2021-01-14 17:34 UTC, nut4k1 commented
hints if needed

https://gist.github.com/nut4k1/fb31e79e24998934e82b0ade3f973a1e

2021-01-14 18:47 UTC, HolyHol commented on test/exercise/arrays/solution.rb
> +          list[0] # base case
Sorry, i didn't get

2021-01-14 18:51 UTC, HolyHol commented on test/exercise/arrays/solution.rb
> +        sub_array = replaces_positive_array(array[1..-1], max_array_new)
In which cases? Tests are passing

2021-01-14 19:00 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +          list[0] # base case
code should work with any size. check my attachment below
or text me in tg

2021-01-14 19:00 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +        sub_array = replaces_positive_array(array[1..-1], max_array_new)
I've copied your code and it failed

2021-01-14 19:03 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +        sub_array = replaces_positive_array(array[1..-1], max_array_new)
yep, sorry. I've tried again and it works. but still using recursive here is not a best option

2021-01-14 19:21 UTC, HolyHol commented on test/exercise/arrays/solution.rb
> +          list[0] # base case
It's working, I can't get the issue

2021-01-14 19:25 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +          list[0] # base case
It's working. But the way HOW it works also matters

2021-01-14 20:15 UTC, HolyHol commented on test/exercise/arrays/solution.rb
> +      return -1
i check and it's working like log2(N)

```ruby
irb(main):001:1* def search(_array, _query)
irb(main):002:1*   # Реализовать двоичный поиск
irb(main):003:1*   # Функция должна возвращать индекс элемента
irb(main):004:1*   low = 0
irb(main):005:1*   high = _array.length - 1
irb(main):006:1*   count = 0
irb(main):007:1*
irb(main):008:2*   while low <= high
irb(main):009:2*     mid = (low + high) / 2
irb(main):010:2*     guess = _array[mid]
irb(main):011:2*     count = count + 1
irb(main):012:2*
irb(main):013:3*     if guess == _query
irb(main):014:3*       puts count
irb(main):015:3*       return mid
irb(main):016:3*
irb(main):017:3*     elsif guess > _query
irb(main):018:3*       high = mid - 1
irb(main):019:3*
irb(main):020:3*     else
irb(main):021:3*       low = mid + 1
irb(main):022:2*     end
irb(main):023:1*   end
irb(main):024:1*   -1
irb(main):025:0> end
=> :search
irb(main):026:0> search((1..10000).to_a, 1000)
11
=> 999
irb(main):027:0>
```

2021-01-14 20:46 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +      return -1
so just change a condition for the loop :)

2021-01-15 14:01 UTC, HolyHol commented on test/exercise/arrays/solution.rb
> +      return -1
I really don't understand what do u mean :(

2021-01-15 14:55 UTC, nut4k1 commented on test/exercise/arrays/solution.rb
> +      return -1
ok, then just apply a few style fixes and roll forward

2021-01-15 14:56 UTC, nut4k1 approved these changes

2021-01-19 09:26 UTC, merged